### ISSUE TITLE
Corrupt G-Zip compressed data 

### ISSUE THREAD

**Issue by tischi** [mobie-org/mobie#18] opened 2020-10-26 06:50 UTC
@constantinpape @K-Meech 

Yannick was reporting below error, have you seen this before or an idea what this could be due to?

> ...opening the FIB SEM data from here (https://github.com/mobie/covid-em-datasets), I get the error below. 
When opening the other dataset (https://github.com/mobie/covid-tomo-datasets) I get also errors, “java.lang.RuntimeException”.  Any idea about what may cause this? Could that be because there was a recent update of Java?

```
[INFO] Reading available sites from https://imagej.net/
Adding source: fibsem-raw...
java.util.concurrent.ExecutionException: java.io.IOException: Gzip-compressed data is corrupt
	at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:112)
	at net.imglib2.cache.util.LoaderCacheKeyAdapter.get(LoaderCacheKeyAdapter.java:20)
	at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:43)
	at net.imglib2.cache.ref.WeakRefVolatileCache.getBlocking(WeakRefVolatileCache.java:451)
	at net.imglib2.cache.ref.WeakRefVolatileCache.access$000(WeakRefVolatileCache.java:20)
	at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:498)
	at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:475)
	at net.imglib2.cache.queue.FetcherThreads$Fetcher.run(FetcherThreads.java:177)
Caused by: java.io.IOException: Gzip-compressed data is corrupt
	at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.read(GzipCompressorInputStream.java:313)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readFully(DataInputStream.java:169)
	at org.janelia.saalfeldlab.n5.DefaultBlockReader.read(DefaultBlockReader.java:51)
	at org.janelia.saalfeldlab.n5.DefaultBlockReader.readBlock(DefaultBlockReader.java:87)
	at org.janelia.saalfeldlab.n5.s3.N5AmazonS3Reader.readBlock(N5AmazonS3Reader.java:235)
	at de.embl.cba.mobie.n5.N5ImageLoader$N5CacheArrayLoader.loadArray(N5ImageLoader.java:321)
	at bdv.img.cache.VolatileGlobalCellCache.lambda$createImg$1(VolatileGlobalCellCache.java:246)
	at net.imglib2.cache.util.LoaderCacheKeyAdapter.lambda$get$0(LoaderCacheKeyAdapter.java:22)
	at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:102)
	... 7 more
	Suppressed: com.amazonaws.SdkClientException: Unable to verify integrity of data download.  Client calculated content hash didn't match hash calculated by Amazon S3.  The data may be corrupt.
		at com.amazonaws.services.s3.internal.DigestValidationInputStream.validateMD5Digest(DigestValidationInputStream.java:79)
		at com.amazonaws.services.s3.internal.DigestValidationInputStream.read(DigestValidationInputStream.java:49)
		at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:84)
		at com.amazonaws.services.s3.internal.S3AbortableInputStream.read(S3AbortableInputStream.java:99)
		at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:84)
		at org.janelia.saalfeldlab.n5.s3.N5AmazonS3Reader$S3ObjectInputStreamDrain.read(N5AmazonS3Reader.java:88)
		at org.janelia.saalfeldlab.n5.s3.N5AmazonS3Reader$S3ObjectInputStreamDrain.close(N5AmazonS3Reader.java:95)
		at java.io.FilterInputStream.close(FilterInputStream.java:181)
		at java.io.BufferedInputStream.close(BufferedInputStream.java:483)
		at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.close(GzipCompressorInputStream.java:394)
		at org.janelia.saalfeldlab.n5.DefaultBlockReader.read(DefaultBlockReader.java:52)
		... 13 more
```

**Comment by constantinpape** [comment] 2020-10-26 08:30
I get different errors that seem to be related to the s3 access issues:
```
com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: 16417D945ACE82F9; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1811)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1395)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1371)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5062)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5008)
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1338)
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1312)
	at com.amazonaws.services.s3.AmazonS3Client.doesObjectExist(AmazonS3Client.java:1393)
	at org.janelia.saalfeldlab.n5.s3.N5AmazonS3Reader.getAttributes(N5AmazonS3Reader.java:233)
	at org.janelia.saalfeldlab.n5.AbstractGsonReader.getAttribute(AbstractGsonReader.java:128)
	at org.janelia.saalfeldlab.n5.N5Reader.getVersion(N5Reader.java:206)
	at org.janelia.saalfeldlab.n5.s3.N5AmazonS3Reader.<init>(N5AmazonS3Reader.java:210)
	at org.janelia.saalfeldlab.n5.s3.N5AmazonS3Reader.<init>(N5AmazonS3Reader.java:132)
	at de.embl.cba.mobie.n5.N5S3ImageLoader$N5AmazonS3ReaderCreator.create(N5S3ImageLoader.java:78)
	at de.embl.cba.mobie.n5.N5S3ImageLoader.<init>(N5S3ImageLoader.java:111)
	at de.embl.cba.mobie.n5.XmlIoN5S3ImageLoader.fromXml(XmlIoN5S3ImageLoader.java:82)
	at de.embl.cba.mobie.n5.XmlIoN5S3ImageLoader.fromXml(XmlIoN5S3ImageLoader.java:44)
	at mpicbg.spim.data.generic.sequence.XmlIoAbstractSequenceDescription.fromXml(XmlIoAbstractSequenceDescription.java:111)
	at mpicbg.spim.data.generic.XmlIoAbstractSpimData.fromXml(XmlIoAbstractSpimData.java:153)
	at mpicbg.spim.data.generic.XmlIoAbstractSpimData.load(XmlIoAbstractSpimData.java:95)
	at de.embl.cba.bdv.utils.BdvUtils.openSpimData(BdvUtils.java:1393)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.initSpimData(LazySpimSource.java:89)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.wrappedVolatileSource(LazySpimSource.java:66)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getType(LazySpimSource.java:137)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getType(LazySpimSource.java:48)
	at bdv.util.BdvFunctions.addSource(BdvFunctions.java:581)
	at bdv.util.BdvFunctions.show(BdvFunctions.java:196)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.showIntensitySource(SourcesPanel.java:387)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.addSourceToViewer(SourcesPanel.java:364)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.addSourceToPanelAndViewer(SourcesPanel.java:339)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.addSourceToPanelAndViewer(SourcesPanel.java:296)
	at de.embl.cba.mobie.bookmark.BookmarksManager.addSourcesToPanelAndViewer(BookmarksManager.java:53)
	at de.embl.cba.mobie.bookmark.BookmarksManager.setView(BookmarksManager.java:35)
	at de.embl.cba.mobie.ui.viewer.MoBIEViewer.<init>(MoBIEViewer.java:87)
	at de.embl.cba.mobie.ui.viewer.MoBIEViewer.<init>(MoBIEViewer.java:52)
	at de.embl.cba.mobie.ui.command.OpenPlatyBrowserCommand.run(OpenPlatyBrowserCommand.java:16)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by K-Meech** [comment] 2020-10-26 09:20
I get the same errors as Constantin. Same if I try to open the platybrowser data too.

**Comment by tischi** [comment] 2020-10-26 09:49
I sent a mail to IT support.

**Comment by tischi** [comment] 2020-10-26 11:15
answer from IT:
```
We have just hit a bug in S3 storage and we are not sure whether there
was some data loose or not, can you check whether platy browser is still
working fine and probable check the data which is in there?
```
Could you all check again?

**Comment by constantinpape** [comment] 2020-10-26 12:14
I don't think it's restored yet: still the same issue when trying to open the platybrowser and I also can't access anything via minio:
```
pape@gpu6:~$ mc ls embl
mc: <ERROR> Unable to list folder. The Access Key Id you provided does not exist in our records.
```

**Comment by titansmc** [comment] 2020-10-26 12:31
I am trying to fix errors on the filesystem and then bring the server online, but it may happen that I need to re create credentials and policies for buckets

**Comment by constantinpape** [comment] 2020-10-27 07:51
Some of the data is accessible again and the platybrowser is starting now.
I also tried the `covid-tomo-dataset`, but there I still got some of the Gzip compression errors.
@titansmc mentioned that they still need to replace some drives today in order to restore all the data; let's hope that this fixes the error.

**Comment by constantinpape** [comment] 2020-10-28 07:56
Access to the s3 data via the mobie plugin is down again, now failing with
```
[ERROR] Module threw exception
com.amazonaws.services.s3.model.AmazonS3Exception: Bad Request (Service: Amazon S3; Status Code: 400; Error Code: 400 Bad Request; Request ID: null; S3 Extended Request ID: null), S3 Extended Request ID: null
```
See https://github.com/mobie/platybrowser-datasets/issues/76 for full error message.

**Comment by tischi** [comment] 2020-10-28 08:37
@constantinpape @martinschorb
Am I right in the assessment that we have all data on the group shares, and, once the S3 is running again, we, worst case, "just" would need to copy everything back to the S3?

**Comment by martinschorb** [comment] 2020-10-28 08:45
> @constantinpape @martinschorb
> Am I right in the assessment that we have all data on the group shares, and, once the S3 is running again, we, worst case, "just" would need to copy everything back to the S3?

The covid fibsem data (n5 format) is no longer on the group share. We would also need to convert it again.

**Comment by constantinpape** [comment] 2020-10-28 08:45
> > @constantinpape @martinschorb
> > Am I right in the assessment that we have all data on the group shares, and, once the S3 is running again, we, worst case, "just" would need to copy everything back to the S3?
> 
> The covid fibsem data (n5 format) is no longer on the group share. We would also need to convert it again.

For platy and covid-tomo we still have all the n5s.

**Comment by tischi** [comment] 2020-10-28 08:53
> The covid fibsem data (n5 format) is no longer on the group share. We would also need to convert it again.

@martinschorb  Maybe, preemptively,  start this conversion process already now, so we could act fast in case we need to?

**Comment by yanschwab** [comment] 2020-10-28 09:29
Thanks all for acting on this so quickly. FYI, with the hope that MobIE is up and running again soon, the paper linking to the covid-data might get online already mid next week. It would be fantastic if things run smoothly by then.

**Comment by titansmc** [comment] 2020-10-28 10:30
Another critical release has been made for MinIO and we are going to upgrade to, this one is supposed to rebuild the data just fine, so no data loose is expected. However we are now facing a different issue at the physical network layer and our team is working on it, but it is also possible that until tomorrow early morning they are not able to replace the parts. Since we have dual cards I am trying to bring it to live with only one interface.

**Comment by constantinpape** [comment] 2020-10-29 12:35
A short update on this:
- The platybrowser is back up and seems to be working as expected (cc @HernandoMV).
- The covid datasets are also back up, but we still have the `corrupt gzip data` error there. I am not sure if this is due to data loss or some unrelated issue (maybe connected due to the recent fiji update). I will investigate.

**Comment by titansmc** [comment] 2020-10-29 12:58
Public datasets should be now available.

**Comment by yanschwab** [comment] 2020-10-29 13:31
I tried as well, I also see the gzip data error in the console, when opening the either the FIB or the tomo datasets. At least now something is loaded and I see an image. But the system gets very very slow.

**Comment by constantinpape** [comment] 2020-10-29 13:34
> I tried as well, I also see the gzip data error in the console, when opening the either the FIB or the tomo datasets. At least now something is loaded and I see an image. But the system gets very very slow.

Yes, I am investigating this now, will let you know once I have an idea what's going wrong.

**Comment by titansmc** [comment] 2020-10-29 14:14
I did a change on the load balancer to reuse connections, can you confirm that performance is better now? like before?

**Comment by constantinpape** [comment] 2020-10-29 14:17
> I did a change on the load balancer to reuse connections, can you confirm that performance is better now? like before?

The issue is that we get some data corruption errors for some of the data and this negatively impacts performance because of the subsequent error handling in FIJI.

I am not quite sure what causes this issue; if it's due to actual data corruption or due to some other issues (maybe recent updates in FIJI). I am re-uploading a dataset now to check this.

**Comment by constantinpape** [comment] 2020-10-29 14:40
Re-uploading the data fixes the issue. So maybe there was some data corruption after all?
I will upload all data again for the covid-tomo-dataset today.

@yanschwab I will let you know once it is all replaced, maybe you can then check if it also works on your side?

I can also check for the sbem data if all the data to generate the n5s again is still there. Otherwise I will need to coordinate with @martinschorb.

**Comment by yanschwab** [comment] 2020-10-29 14:43
thank you so much! I'll wait for your signal a go ahead with the crash test ...

**Comment by constantinpape** [comment] 2020-10-29 17:03
@yanschwab 
I reuploaded all the data for `covid-tomo-datasets` again and it is working properly for me.
So all good to go for the crash testing ;).

For the `covid-fibsem-datasets`I need to coordinate with Martin or Julian because I don't understand the data organisation; I wrote to them and I hope we can figure it out tomorrow.

**Comment by yanschwab** [comment] 2020-10-29 17:13
Success! It's working smoothly on my side as well. Thank you very much Constantine

**Comment by tischi** [comment] 2020-10-30 08:38
@constantinpape @titansmc 
Thanks a lot for acting so fast! Really really great!
🚀

**Comment by martinschorb** [comment] 2020-10-30 09:23
A  general question concerning the issue:

What is the backup strategy for the object-based storage? Is there anything similar to FS snapshots to be implemented?
In the long run it should not only exist parallel to group shares but at some point complement or even replace them...

**Comment by yanschwab** [comment] 2020-10-30 09:35
@martinschorb, when will you be able to upload the FIBSEM data? For now it is still showing the Gzip thing.

**Comment by constantinpape** [comment] 2020-10-30 09:37
> @martinschorb, when will you be able to upload the FIBSEM data? For now it is still showing the Gzip thing.

I am converting the data right now, I hope it's reuploaded by this evening.
Will let you know once it's there.

**Comment by martinschorb** [comment] 2020-10-30 09:38
> I am converting the data right now, I hope it's reuploaded by this evening.

Will you do it in place?

I have cleaned up the directory, so it should behave as before. Let me know if there are issues with access rights.

**Comment by yanschwab** [comment] 2020-10-30 09:40
> > @martinschorb, when will you be able to upload the FIBSEM data? For now it is still showing the Gzip thing.
> 
> I am converting the data right now, I hope it's reuploaded by this evening.
> Will let you know once it's there.

That's great. Very very good timing. The paer was resubmitted yesterday evening. Release probably mid next week

**Comment by titansmc** [comment] 2020-10-30 10:26
> A general question concerning the issue:
> 
> What is the backup strategy for the object-based storage? Is there anything similar to FS snapshots to be implemented?
> In the long run it should not only exist parallel to group shares but at some point complement or even replace them...

Let's discuss this in private, I will send you guys an email.

**Comment by constantinpape** [comment] 2020-11-02 07:59
I have uploaded most of the data for `covid-em`, but it seems there are some new issues with the s3 server.
Will let you know once there is any update.

**Comment by constantinpape** [comment] 2020-11-02 23:13
@yanschwab there were some unexpected issues with the `covid-em-dataset`, but now everything is re-uploaded and  seems to be working properly again.
So ready for you to test ;).

**Comment by yanschwab** [comment] 2020-11-03 07:15
> @yanschwab there were some unexpected issues with the `covid-em-dataset`, but now everything is re-uploaded and seems to be working properly again.
> So ready for you to test ;).

Thanks @constantinpape The data is now nicely accessible. Yet, I have the feeling we are having troubles with the segmentation file, that shows object of weird shape. Does Julian have access to this thread? I will ask him to have a look

**Comment by constantinpape** [comment] 2020-11-09 15:47
Re-uploading the data has solved the issues for the two covid datasets.
There still might be some issues with the platy dataset, see https://github.com/mobie/platybrowser-datasets/issues/78, but we can deal with this seperately, so i am closing this for now.

**Closed as completed by constantinpape** 2020-11-09 15:47 UTC
Labels: bug
